spring.datasource.url=jdbc:postgresql://localhost:5432/ai_customer_support_db
spring.datasource.username=postgres
spring.datasource.password=Mora

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

# JWT Configuration
app.jwt.secret=AI-Customer-Support-Super-Secret-Key-2026-Production
app.jwt.expiration-ms=86400000

# Default Admin Configuration
app.admin.email=admin@aicustomersupport.com
app.admin.password=Admin@123456